probset2/config/routes.rb
Probset2::Application.routes.draw do
  resources :clickers

end

probset2/app/models/clicker.rb
class Clicker < ActiveRecord::Base
end

probset2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

probset2/app/controllers/clickers_controller.rb
class ClickersController < ApplicationController
  # GET /clickers
  # GET /clickers.xml
  def index
    @clickers = Clicker.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clickers }
    end
  end

  # GET /clickers/1
  # GET /clickers/1.xml
  def show
    @clicker = Clicker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @clicker }
    end
  end

  # GET /clickers/new
  # GET /clickers/new.xml
  def new
    @clicker = Clicker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @clicker }
    end
  end

  # GET /clickers/1/edit
  def edit
    @clicker = Clicker.find(params[:id])
  end

  # POST /clickers
  # POST /clickers.xml
  def create
    @clicker = Clicker.new(params[:clicker])

    respond_to do |format|
      if @clicker.save
        format.html { redirect_to(@clicker, :notice => 'Clicker was successfully created.') }
        format.xml  { render :xml => @clicker, :status => :created, :location => @clicker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @clicker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clickers/1
  # PUT /clickers/1.xml
  def update
    @clicker = Clicker.find(params[:id])

    respond_to do |format|
      if @clicker.update_attributes(params[:clicker])
        format.html { redirect_to(@clicker, :notice => 'Clicker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @clicker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clickers/1
  # DELETE /clickers/1.xml
  def destroy
    @clicker = Clicker.find(params[:id])
    @clicker.destroy

    respond_to do |format|
      format.html { redirect_to(clickers_url) }
      format.xml  { head :ok }
    end
  end
end

probset2/app/helpers/application_helper.rb
module ApplicationHelper
end

probset2/app/helpers/clickers_helper.rb
module ClickersHelper
end

probset2/app/views/clickers/_form.html.erb
<%= form_for(@clicker) do |f| %>
  <% if @clicker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clicker.errors.count, "error") %> prohibited this clicker from being saved:</h2>

      <ul>
      <% @clicker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :choices %><br />
    <%= f.text_area :choices %>
  </div>
  <div class="field">
    <%= f.label :answers %><br />
    <%= f.text_area :answers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

probset2/app/views/clickers/edit.html.erb
<h1>Editing clicker</h1>

<%= render 'form' %>

<%= link_to 'Show', @clicker %> |
<%= link_to 'Back', clickers_path %>

probset2/app/views/clickers/index.html.erb
<h1>Listing clickers</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Choices</th>
    <th>Answers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clickers.each do |clicker| %>
  <tr>
    <td><%= clicker.question %></td>
    <td><%= clicker.choices %></td>
    <td><%= clicker.answers %></td>
    <td><%= link_to 'Show', clicker %></td>
    <td><%= link_to 'Edit', edit_clicker_path(clicker) %></td>
    <td><%= link_to 'Destroy', clicker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clicker', new_clicker_path %>

probset2/app/views/clickers/new.html.erb
<h1>New clicker</h1>

<%= render 'form' %>

<%= link_to 'Back', clickers_path %>

probset2/app/views/clickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @clicker.question %>
</p>

<p>
  <b>Choices:</b>
  <%= @clicker.choices %>
</p>

<p>
  <b>Answers:</b>
  <%= @clicker.answers %>
</p>


<%= link_to 'Edit', edit_clicker_path(@clicker) %> |
<%= link_to 'Back', clickers_path %>

probset2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Probset2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>