clicker/config/routes.rb
Clicker::Application.routes.draw do
  resources :crs

end

clicker/app/models/crs.rb
class Crs < ActiveRecord::Base
end

clicker/app/controllers/crs_controller.rb
class CrsController < ApplicationController
  # GET /crs
  # GET /crs.xml
  def index
    @crs = Crs.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @crs }
    end
  end

  # GET /crs/1
  # GET /crs/1.xml
  def show
    @cr = Crs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cr }
    end
  end

  # GET /crs/new
  # GET /crs/new.xml
  def new
    @cr = Crs.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cr }
    end
  end

  # GET /crs/1/edit
  def edit
    @cr = Crs.find(params[:id])
  end

  # POST /crs
  # POST /crs.xml
  def create
    @cr = Crs.new(params[:cr])

    respond_to do |format|
      if @cr.save
        format.html { redirect_to(@cr, :notice => 'Crs was successfully created.') }
        format.xml  { render :xml => @cr, :status => :created, :location => @cr }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cr.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /crs/1
  # PUT /crs/1.xml
  def update
    @cr = Crs.find(params[:id])

    respond_to do |format|
      if @cr.update_attributes(params[:cr])
        format.html { redirect_to(@cr, :notice => 'Crs was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cr.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /crs/1
  # DELETE /crs/1.xml
  def destroy
    @cr = Crs.find(params[:id])
    @cr.destroy

    respond_to do |format|
      format.html { redirect_to(crs_index_url) }
      format.xml  { head :ok }
    end
  end
end

clicker/app/helpers/c_rs_helper.rb
module CRsHelper
end

clicker/app/helpers/crs_helper.rb
module CrsHelper
end

clicker/app/views/crs/_form.html.erb
<%= form_for(@cr) do |f| %>
  <% if @cr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cr.errors.count, "error") %> prohibited this cr from being saved:</h2>

      <ul>
      <% @cr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :choices %><br />
    <%= f.text_area :choices %>
  </div>
  <div class="field">
    <%= f.label :answers %><br />
    <%= f.text_area :answers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clicker/app/views/crs/edit.html.erb
<h1>Editing cr</h1>

<%= render 'form' %>

<%= link_to 'Show', @cr %> |
<%= link_to 'Back', crs_index_path %>

clicker/app/views/crs/index.html.erb
<h1>Listing crs</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Choices</th>
    <th>Answers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crs.each do |cr| %>
  <tr>
    <td><%= cr.question %></td>
    <td><%= cr.choices %></td>
    <td><%= cr.answers %></td>
    <td><%= link_to 'Show', cr %></td>
    <td><%= link_to 'Edit', edit_cr_path(cr) %></td>
    <td><%= link_to 'Destroy', cr, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crs', new_cr_path %>

clicker/app/views/crs/new.html.erb
<h1>New cr</h1>

<%= render 'form' %>

<%= link_to 'Back', crs_index_path %>

clicker/app/views/crs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @cr.question %>
</p>

<p>
  <b>Choices:</b>
  <%= @cr.choices %>
</p>

<p>
  <b>Answers:</b>
  <%= @cr.answers %>
</p>


<%= link_to 'Edit', edit_cr_path(@cr) %> |
<%= link_to 'Back', crs_index_path %>

clicker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clicker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>